### ISSUE TITLE
прорисовать канализацию МЖКП Нептун

### ISSUE THREAD

**Issue by user2589** [user2589/karta#12]
файл без привязки http://kyrie.ru/karta/%d0%b2%d0%be%d0%b4%d0%be%d0%be%d1%82%d0%b2%d0%b5%d0%b4%d0%b5%d0%bd%d0%b8%d0%b5/%d0%b7%d0%b4%d0%b0%d0%bd%d0%b8%d0%b5%20%d0%9c%d0%96%d0%9a%d0%9f%20%d0%9d%d0%b5%d0%bf%d1%82%d1%83%d0%bd.jpg

**Comment by user2589** [comment]
на этой карте канализация - красным цветом

**Comment by alehinazoya** [comment]
не могу найти этот участок на карте

**Comment by mashkovskaya** [comment]
за Аскольдом за ж/д дорогой ул. Луговая, должен быть там участок

**Comment by alehinazoya** [comment]
да нашла с помощью http://www.primcenter.ru/maps#, на рабочей карте улица не правильно указана

**Comment by user2589** [comment]
http://geojson.io/#id=gist:anonymous/2bb6dcdfd6deab2f97a4&map=17/44.16763/133.25529
