### ISSUE TITLE
прорисовать водоснабжение здание МЖКП Нептун

### ISSUE THREAD

**Issue by user2589** [user2589/karta#13]
файл без привязки http://kyrie.ru/karta/%d0%b2%d0%be%d0%b4%d0%be%d0%be%d1%82%d0%b2%d0%b5%d0%b4%d0%b5%d0%bd%d0%b8%d0%b5/%d0%b7%d0%b4%d0%b0%d0%bd%d0%b8%d0%b5%20%d0%9c%d0%96%d0%9a%d0%9f%20%d0%9d%d0%b5%d0%bf%d1%82%d1%83%d0%bd.jpg

**Comment by alehinazoya** [comment]
готово!
