### ISSUE TITLE
прорисовать водоснабжение ул. Береговая

### ISSUE THREAD

**Issue by user2589** [user2589/karta#14]
файл без привязки http://kyrie.ru/karta/%d0%b2%d0%be%d0%b4%d0%be%d0%be%d1%82%d0%b2%d0%b5%d0%b4%d0%b5%d0%bd%d0%b8%d0%b5/%d1%83%d0%bb.%20%d0%91%d0%b5%d1%80%d0%b5%d0%b3%d0%be%d0%b2%d0%b0%d1%8f.jpg

Канализации у них нет, только водоснабжение

**Comment by alehinazoya** [comment]
соединила два дома, которые были соединены между собой с общей схемой
