### ISSUE TITLE
прорисовать канализацию Пограничная 72

### ISSUE THREAD

**Issue by user2589** [user2589/karta#21]
файл без привязки
http://kyrie.ru/karta/%D0%B2%D0%BE%D0%B4%D0%BE%D0%BE%D1%82%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D0%B5/%d0%9f%d0%be%d0%b3%d1%80%d0%b0%d0%bd%d0%b8%d1%87%d0%bd%d0%b0%d1%8f%2072.jpg

**Comment by alehinazoya** [comment]
отправила на эл. почту
